language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  
script: ant test
env: 
  global: 
     - secure: "StaRWxgVW55YXMetUfL91rGDHJCBC0e3Nv9qYx5jg2aa9H0BIYhJ8vYtDXbKFEeGXWRnlLdPVclzRiIMdYQTZaBrjHxWVzE9N5stIyIq/Ik5hvkRs3h78ICSsDJB7SAun+aYv4vV/2kR44B0YiOhWZehV3IhAWO1Csd4HDjiQHY="
     - API_TEST_KEY: 0dcb0c6a3dcddace93de405fb98857b7
     - API_PUBLIC_TEST_KEY: 07558773223ff498c4ab0ca581551453

before_install: composer self-update
install: composer install
